const state={data:null};const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];const setText=(s,v)=>{const e=$(s);if(e)e.textContent=v};const esc=(v="")=>String(v).replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));const phaseLabel=p=>`P${String(p.number).padStart(2,"0")}`;
function renderMetrics(d){const c=d.labs.filter(l=>l.complete).length,t=d.labs.length,v=d.labs.reduce((s,l)=>s+(l.verified_count||0),0),a=d.phases.find(p=>p.status==="active")||d.phases.find(p=>p.status==="pending")||d.phases.at(-1);setText("#metric-completed",c);setText("#metric-total",`of ${t} discovered`);setText("#metric-verified",v);setText("#metric-phase",a?phaseLabel(a):"—");setText("#metric-phase-name",a?a.name:"no phase");setText("#metric-git",d.git.dirty?"DIRTY":"CLEAN");setText("#metric-branch",d.git.branch||"unknown branch");const p=d.phases.length?Math.round(d.phases.filter(x=>x.status==="done").length/d.phases.length*100):0;setText("#progress-label",`${p}%`)}
function renderMission(d){const i=d.labs.find(l=>!l.complete),latest=d.labs.at(-1);if(i){setText("#mission-title",`${i.id} — ${i.title}`);setText("#mission-subtitle","Sıradaki keşfedilen laboratuvar henüz tamamlanmamış görünüyor.")}else if(latest){setText("#mission-title",`${latest.id} tamamlandı`);setText("#mission-subtitle","Repo temiz. Bir sonraki laboratuvar için hazır.")}else{setText("#mission-title","CyberLab hazır");setText("#mission-subtitle","Henüz laboratuvar keşfedilmedi.")}}
function renderPhases(d){$("#phase-list").innerHTML=d.phases.map(p=>{const w=p.status==="done"?100:p.status==="active"?Math.max(18,p.progress||35):0;return `<div class="phase-row ${p.status==="done"?"done":""}"><div class="phase-num">${esc(phaseLabel(p))}</div><div><div class="phase-name">${esc(p.name)}</div><div class="bar"><span style="width:${w}%"></span></div></div><div class="phase-state">${esc(p.status.toUpperCase())}</div></div>`}).join("")}
function renderTelemetry(d){const lines=[`[server] ${d.server.host}:${d.server.port}`,`[repo] ${d.git.branch} @ ${d.git.head_short||"unknown"}`,`[tree] ${d.labs.length} lab(s) discovered`,`[findings] ${d.labs.reduce((s,l)=>s+(l.verified_count||0),0)} VERIFIED marker(s)`,`[workspace] ${d.git.dirty?"uncommitted changes present":"working tree clean"}`,`[mode] localhost educational environment`];$("#telemetry").innerHTML=lines.map(x=>`<div><span class="prompt">›</span>${esc(x)}</div>`).join("")}
function renderLabs(d,q=""){q=q.trim().toLowerCase();const labs=d.labs.filter(l=>`${l.id} ${l.title} ${l.phase_name}`.toLowerCase().includes(q)),el=$("#lab-grid");if(!labs.length){el.innerHTML='<article class="lab-card"><h3>Sonuç yok</h3><p>Arama ölçütüne uyan laboratuvar bulunamadı.</p></article>';return}el.innerHTML=labs.map(l=>`<article class="lab-card ${l.complete?"done":""}"><span class="badge ${l.complete?"":"dim"}">${l.complete?"COMPLETE":"IN PROGRESS"}</span><h3>${esc(l.id)} — ${esc(l.title)}</h3><p>${esc(l.summary||"Laboratuvar klasörü keşfedildi.")}</p><div class="lab-meta"><span>${esc(l.phase_name)}</span><span>${l.verified_count||0} VERIFIED</span></div></article>`).join("")}
function renderActivity(d){const el=$("#activity-list");if(!d.git.commits.length){el.innerHTML='<div class="activity-item"><span class="sha">—</span><span class="activity-msg">Commit bulunamadı</span></div>';return}el.innerHTML=d.git.commits.map(c=>`<div class="activity-item"><span class="sha">${esc(c.sha)}</span><span class="activity-msg">${esc(c.message)}</span><span class="activity-time">${esc(c.date||"")}</span></div>`).join("")}
function render(d){state.data=d;setText("#server-status","ONLINE");setText("#last-sync",`sync ${new Date().toLocaleTimeString("tr-TR",{hour:"2-digit",minute:"2-digit",second:"2-digit"})}`);renderMission(d);renderMetrics(d);renderPhases(d);renderTelemetry(d);renderLabs(d,$("#lab-search")?.value||"");renderActivity(d)}
async function refresh(){setText("#server-status","SYNCING");try{const r=await fetch("/api/status",{cache:"no-store"});if(!r.ok)throw new Error(`HTTP ${r.status}`);render(await r.json())}catch(e){setText("#server-status","OFFLINE");$("#telemetry").innerHTML=`<div><span class="prompt">!</span>${esc(e.message)}</div><div>Dashboard'u dashboard/serve.py üzerinden çalıştır.</div>`}}
const roles={red:{icon:"R",kicker:"OFFENSIVE VIEW",title:"Red Team",copy:"Yetkili laboratuvar hedeflerinde saldırı yüzeyini, protokol davranışını ve kontrollü sömürü zincirini anlamak."},victim:{icon:"V",kicker:"IMPACT VIEW",title:"Victim Perspective",copy:"Aynı olayın hedef sistemde oluşturduğu belirtileri, servis davranışını, logları ve kullanıcı etkisini gözlemlemek."},blue:{icon:"B",kicker:"DEFENSIVE VIEW",title:"Blue Team",copy:"Saldırıyı tespit etmek, kanıtları yorumlamak, olayı sınırlandırmak, sistemi sertleştirmek ve tekrarını önlemek."}};
$$('.nav-item').forEach(b=>b.addEventListener('click',()=>{$$('.nav-item').forEach(x=>x.classList.remove('active'));b.classList.add('active');$$('.view').forEach(v=>v.classList.toggle('active-view',v.id===b.dataset.target))}));$$('.role-tab').forEach(b=>b.addEventListener('click',()=>{$$('.role-tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');const r=roles[b.dataset.role];$('.role-icon').textContent=r.icon;setText('#role-kicker',r.kicker);setText('#role-title',r.title);setText('#role-copy',r.copy)}));$('#refresh-btn').addEventListener('click',refresh);$('#lab-search').addEventListener('input',e=>{if(state.data)renderLabs(state.data,e.target.value)});refresh();
